### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Yoiapak96** [AbhiTheModder/gemini-ai-telegram#5]
Where to fill the key api and etc like that? I'm confused

**Comment by AbhiTheModder** [comment]
@Yoiapak96 depends on how you want to use in your bot either put into your environment vars and just call through `os.environ["API_KEY"]` or put inside an `.env` file and get from there for example through `environs` python package see my `ubai.py` files for that example OR if just using for simple/personal tests you can put at API_KEY place where i've qouted in files too

**Comment by Yoiapak96** [comment]
Thank you.
